IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE NAME = 'SP_SEARCHEMPLOYEENOTINDIVISION')
BEGIN
	DROP PROC SP_SEARCHEMPLOYEENOTINDIVISION
END
GO
CREATE PROC SP_SEARCHEMPLOYEENOTINDIVISION
	@SECID VARCHAR
AS 
BEGIN
	IF EXISTS (SELECT * FROM SECTION WHERE SECID = @SECID)
	BEGIN
		SELECT * FROM EMPLOYEE
		WHERE EMID NOT IN (
			SELECT A.EMID
			FROM EMPLOYEE AS A 
			INNER JOIN DEPARTMENTS AS B  ON A.DEP_ID = B.DEP_ID
	        --INNER JOIN SECTION AS C  ON B.DEP_ID = C.DEPID
	        INNER JOIN DIVISION AS D ON a.EMID = D.EMID
		
			WHERE D.SECID = @SECID
			)
	END
END


	