IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE NAME = 'SP_SEARCHEMPLOYEEINDIVISION')
BEGIN
	DROP PROC SP_SEARCHEMPLOYEEINDIVISION
END
GO
CREATE PROC SP_SEARCHEMPLOYEEINDIVISION
	@SECID VARCHAR

AS 
BEGIN
	IF EXISTS (SELECT * FROM SECTION WHERE SECID = @SECID)
	BEGIN
		SELECT A.EmID,A.NAME 
		FROM EMPLOYEE AS A 
		INNER JOIN DEPARTMENTS AS B 
	     ON A.DEP_ID = B.DEP_ID
	    INNER JOIN SECTION AS C
		 ON B.DEP_ID = C.DEPID
		
	END
END