IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE NAME = 'SP_SEARCHEMPLOYEEINDIVISION')
BEGIN
	DROP PROC SP_SEARCHEMPLOYEEINDIVISION
END
GO
CREATE PROC SP_SEARCHEMPLOYEEINDIVISION
	@SECID VARCHAR
AS 
BEGIN
	IF EXISTS (SELECT * FROM SECTION WHERE SECID = @SECID)
	BEGIN
		SELECT A.NAME ,A.EMID
		FROM EMPLOYEE AS A 
		INNER JOIN DIVISION AS B ON A.EMID = B.EMID
		
	END
END