IF EXISTS ( SELECT * FROM dbo.sysobjects WHERE NAME = 'SP_SEARCHEMPLOYEENOTINDIVISION')
BEGIN
	DROP PROC SP_SEARCHEMPLOYEENOTINDIVISION
END
GO
CREATE PROC SP_SEARCHEMPLOYEENOTINDIVISION
	@SECID VARCHAR
AS 
BEGIN
	IF EXISTS (SELECT * FROM SECTION WHERE SECID = @SECID)
	BEGIN
		SELECT * FROM EMPLOYEE
		WHERE EMID NOT IN (
			SELECT A.EMID
			FROM EMPLOYEE AS A 
			INNER JOIN DIVISION AS B ON A.EMID = B.EMID
			WHERE B.SECID = @SECID
			)
	END
END